while IFS= read -r line; do
pm disable --user "$line" android.autoinstalls.config.samsung
pm disable --user "$line" com.android.apps.tag
pm disable --user "$line" com.android.avatarpicker
pm disable --user "$line" com.android.bips
pm disable --user "$line" com.android.bluetoothmidiservice
pm disable --user "$line" com.android.bookmarkprovider
pm disable --user "$line" com.android.calllogbackup
pm disable --user "$line" com.android.chrome
pm disable --user "$line" com.android.devicediagnostics
pm disable --user "$line" com.android.dreams.phototable
pm disable --user "$line" com.android.dynsystem
pm disable --user "$line" com.android.egg
pm disable --user "$line" com.android.hotwordenrollment.okgoogle
pm disable --user "$line" com.android.hotwordenrollment.xgoogle
pm disable --user "$line" com.android.microdroid.empty_payload
pm disable --user "$line" com.android.ons
pm disable --user "$line" com.android.providers.contactkeys
pm disable --user "$line" com.android.providers.partnerbookmarks
pm disable --user "$line" com.android.providers.userdictionary
pm disable --user "$line" com.android.theme.font.notoserifsource
pm disable --user "$line" com.android.traceur
pm disable --user "$line" com.android.virtualization.terminal
pm disable --user "$line" com.android.wallpaperbackup
pm disable --user "$line" com.facebook.appmanager
pm disable --user "$line" com.facebook.services
pm disable --user "$line" com.facebook.system
pm disable --user "$line" com.google.android.adservices.api
pm disable --user "$line" com.google.android.aicore
pm disable --user "$line" com.google.android.apps.accessibility.voiceaccess
pm disable --user "$line" com.google.android.apps.aiwallpapers
pm disable --user "$line" com.google.android.apps.bard
pm disable --user "$line" com.google.android.apps.messaging
pm disable --user "$line" com.google.android.apps.restore
pm disable --user "$line" com.google.android.apps.tachyon
pm disable --user "$line" com.google.android.appsearch.apk
pm disable --user "$line" com.google.android.as
pm disable --user "$line" com.google.android.as.oss
pm disable --user "$line" com.google.android.configupdater
pm disable --user "$line" com.google.android.federatedcompute
pm disable --user "$line" com.google.android.feedback
pm disable --user "$line" com.google.android.gm
pm disable --user "$line" com.google.android.gms.location.history
pm disable --user "$line" com.google.android.gms.supervision
pm disable --user "$line" com.google.android.googlequicksearchbox
pm disable --user "$line" com.google.android.health.connect.backuprestore
pm disable --user "$line" com.google.android.healthconnect.controller
pm disable --user "$line" com.google.android.ondevicepersonalization.services
pm disable --user "$line" com.google.android.onetimeinitializer
pm disable --user "$line" com.google.android.overlay.modules.healthfitness.forframework
pm disable --user "$line" com.google.android.partnersetup
pm disable --user "$line" com.google.android.printservice.recommendation
pm disable --user "$line" com.google.android.projection.gearhead
pm disable --user "$line" com.google.android.safetycenter.resources
pm disable --user "$line" com.google.android.setupwizard
pm disable --user "$line" com.google.android.tts
pm disable --user "$line" com.google.android.youtube
pm disable --user "$line" com.google.ar.core
pm disable --user "$line" com.google.audio.hearing.visualization.accessibility.scribe
pm disable --user "$line" com.google.mainline.adservices
pm disable --user "$line" com.google.mainline.telemetry
pm disable --user "$line" com.hiya.star
pm disable --user "$line" com.microsoft.appmanager
pm disable --user "$line" com.microsoft.skydrive
pm disable --user "$line" com.mygalaxy.service
pm disable --user "$line" com.qti.qcc
pm disable --user "$line" com.qti.snapdragon.qdcm_ff
pm disable --user "$line" com.qualcomm.location
pm disable --user "$line" com.samsung.SMT
pm disable --user "$line" com.samsung.SMT.lang_en_us_l03
pm disable --user "$line" com.samsung.SMT.lang_zh_cn_l02
pm disable --user "$line" com.samsung.SMT.lang_zh_hk_f00
pm disable --user "$line" com.samsung.SMT.lang_zh_tw_f00
pm disable --user "$line" com.samsung.aasaservice
pm disable --user "$line" com.samsung.accessory.budsunitemgr
pm disable --user "$line" com.samsung.android.aicore
pm disable --user "$line" com.samsung.android.aircommandmanager
pm disable --user "$line" com.samsung.android.allshare.service.mediashare
pm disable --user "$line" com.samsung.android.app.camera.sticker.facearavatar.preload
pm disable --user "$line" com.samsung.android.app.contacts
pm disable --user "$line" com.samsung.android.app.dressroom
pm disable --user "$line" com.samsung.android.app.earphonetypec
pm disable --user "$line" com.samsung.android.app.interpreter
pm disable --user "$line" com.samsung.android.app.omcagent
pm disable --user "$line" com.samsung.android.app.parentalcare
pm disable --user "$line" com.samsung.android.app.routines
pm disable --user "$line" com.samsung.android.app.sketchbook
pm disable --user "$line" com.samsung.android.app.taskedge
pm disable --user "$line" com.samsung.android.app.watchmanagerstub
pm disable --user "$line" com.samsung.android.aremoji
pm disable --user "$line" com.samsung.android.aremojieditor
pm disable --user "$line" com.samsung.android.audiomirroring
pm disable --user "$line" com.samsung.android.authfw
pm disable --user "$line" com.samsung.android.aware.service
pm disable --user "$line" com.samsung.android.bbc.bbcagent
pm disable --user "$line" com.samsung.android.beaconmanager
pm disable --user "$line" com.samsung.android.bixby.agent
pm disable --user "$line" com.samsung.android.bixby.wakeup
pm disable --user "$line" com.samsung.android.bixbyvision.framework
pm disable --user "$line" com.samsung.android.brightnessbackupservice
pm disable --user "$line" com.samsung.android.callbgprovider
pm disable --user "$line" com.samsung.android.cameraxservice
pm disable --user "$line" com.samsung.android.carkey
pm disable --user "$line" com.samsung.android.da.daagent
pm disable --user "$line" com.samsung.android.dbsc
pm disable --user "$line" com.samsung.android.dck.timesync
pm disable --user "$line" com.samsung.android.dialer
pm disable --user "$line" com.samsung.android.dqagent
pm disable --user "$line" com.samsung.android.dsms
pm disable --user "$line" com.samsung.android.dynamiclock
pm disable --user "$line" com.samsung.android.easysetup
pm disable --user "$line" com.samsung.android.fast
pm disable --user "$line" com.samsung.android.forest
pm disable --user "$line" com.samsung.android.game.gametools
pm disable --user "$line" com.samsung.android.globalpostprocmgr
pm disable --user "$line" com.samsung.android.gru
pm disable --user "$line" com.samsung.android.hdmapp
pm disable --user "$line" com.samsung.android.hwresourceshare
pm disable --user "$line" com.samsung.android.hwresourceshare.storage
pm disable --user "$line" com.samsung.android.inputshare
pm disable --user "$line" com.samsung.android.intellivoiceservice
pm disable --user "$line" com.samsung.android.ipsgeofence
pm disable --user "$line" com.samsung.android.kidsinstaller
pm disable --user "$line" com.samsung.android.knox.analytics.uploader
pm disable --user "$line" com.samsung.android.knox.attestation
pm disable --user "$line" com.samsung.android.knox.containercore
pm disable --user "$line" com.samsung.android.knox.kpecore
pm disable --user "$line" com.samsung.android.knox.mpos
pm disable --user "$line" com.samsung.android.knox.pushmanager
pm disable --user "$line" com.samsung.android.knox.zt.framework
pm disable --user "$line" com.samsung.android.mapsagent
pm disable --user "$line" com.samsung.android.mcfds
pm disable --user "$line" com.samsung.android.mcfserver
pm disable --user "$line" com.samsung.android.mdecservice
pm disable --user "$line" com.samsung.android.mdm
pm disable --user "$line" com.samsung.android.mdx
pm disable --user "$line" com.samsung.android.mdx.kit
pm disable --user "$line" com.samsung.android.messaging
pm disable --user "$line" com.samsung.android.mobileservice
pm disable --user "$line" com.samsung.android.mocca
pm disable --user "$line" com.samsung.android.mydevice
pm disable --user "$line" com.samsung.android.net.wifi.wifiguider
pm disable --user "$line" com.samsung.android.networkdiagnostic
pm disable --user "$line" com.samsung.android.nfc
pm disable --user "$line" com.samsung.android.privateaccesstokens
pm disable --user "$line" com.samsung.android.provider.filterprovider
pm disable --user "$line" com.samsung.android.rampart
pm disable --user "$line" com.samsung.android.rubin.app
pm disable --user "$line" com.samsung.android.samsungpass
pm disable --user "$line" com.samsung.android.samsungpassautofill
pm disable --user "$line" com.samsung.android.samsungpositioning
pm disable --user "$line" com.samsung.android.scloud
pm disable --user "$line" com.samsung.android.scpm
pm disable --user "$line" com.samsung.android.sdk.handwriting
pm disable --user "$line" com.samsung.android.sdm.config
pm disable --user "$line" com.samsung.android.sead
pm disable --user "$line" com.samsung.android.server.wifi.mobilewips
pm disable --user "$line" com.samsung.android.service.peoplestripe
pm disable --user "$line" com.samsung.android.service.stplatform
pm disable --user "$line" com.samsung.android.service.tagservice
pm disable --user "$line" com.samsung.android.shortcutbackupservice
pm disable --user "$line" com.samsung.android.smartcallprovider
pm disable --user "$line" com.samsung.android.smartface
pm disable --user "$line" com.samsung.android.smartsuggestions
pm disable --user "$line" com.samsung.android.smartswitchassistant
pm disable --user "$line" com.samsung.android.spayfw
pm disable --user "$line" com.samsung.android.sskds
pm disable --user "$line" com.samsung.android.stickercenter
pm disable --user "$line" com.samsung.android.svcagent
pm disable --user "$line" com.samsung.android.themestore
pm disable --user "$line" com.samsung.android.video
pm disable --user "$line" com.samsung.android.vision.model
pm disable --user "$line" com.samsung.android.visionintelligence
pm disable --user "$line" com.samsung.android.visual.cloudcore
pm disable --user "$line" com.samsung.android.vtcamerasettings
pm disable --user "$line" com.samsung.android.wallpaper.live
pm disable --user "$line" com.samsung.app.newtrim
pm disable --user "$line" com.samsung.cmh
pm disable --user "$line" com.samsung.faceservice
pm disable --user "$line" com.samsung.gpuwatchapp
pm disable --user "$line" com.samsung.ipservice
pm disable --user "$line" com.samsung.knox.securefolder
pm disable --user "$line" com.samsung.petservice
pm disable --user "$line" com.samsung.safetyinformation
pm disable --user "$line" com.samsung.sait.sohservice
pm disable --user "$line" com.samsung.storyservice
pm disable --user "$line" com.samsung.videoscan
pm disable --user "$line" com.sec.android.CcInfo
pm disable --user "$line" com.sec.android.RilServiceModeApp
pm disable --user "$line" com.sec.android.app.SecSetupWizard
pm disable --user "$line" com.sec.android.app.billing
pm disable --user "$line" com.sec.android.app.bluetoothagent
pm disable --user "$line" com.sec.android.app.camera
pm disable --user "$line" com.sec.android.app.chromecustomizations
pm disable --user "$line" com.sec.android.app.desktoplauncher
pm disable --user "$line" com.sec.android.app.factorykeystring
pm disable --user "$line" com.sec.android.app.hwmoduletest
pm disable --user "$line" com.sec.android.app.magnifier
pm disable --user "$line" com.sec.android.app.parser
pm disable --user "$line" com.sec.android.app.qsfastpairoverlay
pm disable --user "$line" com.sec.android.app.quicktool
pm disable --user "$line" com.sec.android.app.samsungapps
pm disable --user "$line" com.sec.android.app.servicemodeapp
pm disable --user "$line" com.sec.android.app.setupwizardlegalprovider
pm disable --user "$line" com.sec.android.app.soundalive
pm disable --user "$line" com.sec.android.app.uwbtest
pm disable --user "$line" com.sec.android.app.ve.vebgm
pm disable --user "$line" com.sec.android.app.vepreload
pm disable --user "$line" com.sec.android.app.wlantest
pm disable --user "$line" com.sec.android.autodoodle.service
pm disable --user "$line" com.sec.android.daemonapp
pm disable --user "$line" com.sec.android.desktopmode.uiservice
pm disable --user "$line" com.sec.android.easyMover
pm disable --user "$line" com.sec.android.easyMover.Agent
pm disable --user "$line" com.sec.android.easyonehand
pm disable --user "$line" com.sec.android.gallery3d
pm disable --user "$line" com.sec.android.iaft
pm disable --user "$line" com.sec.android.llmpolicy
pm disable --user "$line" com.sec.android.mimage.avatarstickers
pm disable --user "$line" com.sec.android.mimage.photoretouching
pm disable --user "$line" com.sec.android.provider.badge
pm disable --user "$line" com.sec.android.smartfpsadjuster
pm disable --user "$line" com.sec.android.widgetapp.easymodecontactswidget
pm disable --user "$line" com.sec.app.RilErrorNotifier
pm disable --user "$line" com.sec.bcservice
pm disable --user "$line" com.sec.epdgtestapp
pm disable --user "$line" com.sec.facatfunction
pm disable --user "$line" com.sec.factory.camera
pm disable --user "$line" com.sec.imslogger
pm disable --user "$line" com.sec.location.nfwlocationprivacy
pm disable --user "$line" com.sec.modem.settings
pm disable --user "$line" com.sec.phone
pm disable --user "$line" com.sec.spp.push
pm disable --user "$line" com.sec.unifiedwfc
pm disable --user "$line" com.sec.usbsettings
pm disable --user "$line" com.sec.vsim.ericssonnsds.webapp
pm disable --user "$line" com.sem.factoryapp
pm disable --user "$line" com.skms.android.agent
pm disable --user "$line" com.swiftkey.swiftkeyconfigurator
pm disable --user "$line" com.tencent.soter.soterserver
pm disable --user "$line" com.touchtype.swiftkey
pm disable --user "$line" com.wsomacp
pm disable --user "$line" org.ifaa.aidl.manager
done <<EOF
$(pm list users | tail -n+2 | sed 's/^.*UserInfo{//; s/:.*}.*$//')
EOF
