while IFS= read -r line; do
pm uninstall --user "$line" android.autoinstalls.config.samsung
pm uninstall --user "$line" com.android.apps.tag
pm uninstall --user "$line" com.android.avatarpicker
pm uninstall --user "$line" com.android.bips
pm uninstall --user "$line" com.android.bluetoothmidiservice
pm uninstall --user "$line" com.android.bookmarkprovider
pm uninstall --user "$line" com.android.calllogbackup
pm uninstall --user "$line" com.android.chrome
pm uninstall --user "$line" com.android.devicediagnostics
pm uninstall --user "$line" com.android.dreams.phototable
pm uninstall --user "$line" com.android.dynsystem
pm uninstall --user "$line" com.android.egg
pm uninstall --user "$line" com.android.hotwordenrollment.okgoogle
pm uninstall --user "$line" com.android.hotwordenrollment.xgoogle
pm uninstall --user "$line" com.android.microdroid.empty_payload
pm uninstall --user "$line" com.android.ons
pm uninstall --user "$line" com.android.providers.contactkeys
pm uninstall --user "$line" com.android.providers.partnerbookmarks
pm uninstall --user "$line" com.android.providers.userdictionary
pm uninstall --user "$line" com.android.theme.font.notoserifsource
pm uninstall --user "$line" com.android.traceur
pm uninstall --user "$line" com.android.virtualization.terminal
pm uninstall --user "$line" com.android.wallpaperbackup
pm uninstall --user "$line" com.facebook.appmanager
pm uninstall --user "$line" com.facebook.services
pm uninstall --user "$line" com.facebook.system
pm uninstall --user "$line" com.google.android.adservices.api
pm uninstall --user "$line" com.google.android.aicore
pm uninstall --user "$line" com.google.android.apps.accessibility.voiceaccess
pm uninstall --user "$line" com.google.android.apps.aiwallpapers
pm uninstall --user "$line" com.google.android.apps.bard
pm uninstall --user "$line" com.google.android.apps.messaging
pm uninstall --user "$line" com.google.android.apps.restore
pm uninstall --user "$line" com.google.android.apps.tachyon
pm uninstall --user "$line" com.google.android.appsearch.apk
pm uninstall --user "$line" com.google.android.as
pm uninstall --user "$line" com.google.android.as.oss
pm uninstall --user "$line" com.google.android.configupdater
pm uninstall --user "$line" com.google.android.federatedcompute
pm uninstall --user "$line" com.google.android.feedback
pm uninstall --user "$line" com.google.android.gm
pm uninstall --user "$line" com.google.android.gms.location.history
pm uninstall --user "$line" com.google.android.gms.supervision
pm uninstall --user "$line" com.google.android.googlequicksearchbox
pm uninstall --user "$line" com.google.android.health.connect.backuprestore
pm uninstall --user "$line" com.google.android.healthconnect.controller
pm uninstall --user "$line" com.google.android.ondevicepersonalization.services
pm uninstall --user "$line" com.google.android.onetimeinitializer
pm uninstall --user "$line" com.google.android.overlay.modules.healthfitness.forframework
pm uninstall --user "$line" com.google.android.partnersetup
pm uninstall --user "$line" com.google.android.printservice.recommendation
pm uninstall --user "$line" com.google.android.projection.gearhead
pm uninstall --user "$line" com.google.android.safetycenter.resources
pm uninstall --user "$line" com.google.android.setupwizard
pm uninstall --user "$line" com.google.android.tts
pm uninstall --user "$line" com.google.android.youtube
pm uninstall --user "$line" com.google.ar.core
pm uninstall --user "$line" com.google.audio.hearing.visualization.accessibility.scribe
pm uninstall --user "$line" com.google.mainline.adservices
pm uninstall --user "$line" com.google.mainline.telemetry
pm uninstall --user "$line" com.hiya.star
pm uninstall --user "$line" com.microsoft.appmanager
pm uninstall --user "$line" com.microsoft.skydrive
pm uninstall --user "$line" com.mygalaxy.service
pm uninstall --user "$line" com.qti.qcc
pm uninstall --user "$line" com.qti.snapdragon.qdcm_ff
pm uninstall --user "$line" com.qualcomm.location
pm uninstall --user "$line" com.samsung.SMT
pm uninstall --user "$line" com.samsung.SMT.lang_en_us_l03
pm uninstall --user "$line" com.samsung.SMT.lang_zh_cn_l02
pm uninstall --user "$line" com.samsung.SMT.lang_zh_hk_f00
pm uninstall --user "$line" com.samsung.SMT.lang_zh_tw_f00
pm uninstall --user "$line" com.samsung.aasaservice
pm uninstall --user "$line" com.samsung.accessory.budsunitemgr
pm uninstall --user "$line" com.samsung.android.aicore
pm uninstall --user "$line" com.samsung.android.aircommandmanager
pm uninstall --user "$line" com.samsung.android.allshare.service.mediashare
pm uninstall --user "$line" com.samsung.android.app.camera.sticker.facearavatar.preload
pm uninstall --user "$line" com.samsung.android.app.contacts
pm uninstall --user "$line" com.samsung.android.app.dressroom
pm uninstall --user "$line" com.samsung.android.app.earphonetypec
pm uninstall --user "$line" com.samsung.android.app.interpreter
pm uninstall --user "$line" com.samsung.android.app.omcagent
pm uninstall --user "$line" com.samsung.android.app.parentalcare
pm uninstall --user "$line" com.samsung.android.app.routines
pm uninstall --user "$line" com.samsung.android.app.sketchbook
pm uninstall --user "$line" com.samsung.android.app.taskedge
pm uninstall --user "$line" com.samsung.android.app.watchmanagerstub
pm uninstall --user "$line" com.samsung.android.aremoji
pm uninstall --user "$line" com.samsung.android.aremojieditor
pm uninstall --user "$line" com.samsung.android.audiomirroring
pm uninstall --user "$line" com.samsung.android.authfw
pm uninstall --user "$line" com.samsung.android.aware.service
pm uninstall --user "$line" com.samsung.android.bbc.bbcagent
pm uninstall --user "$line" com.samsung.android.beaconmanager
pm uninstall --user "$line" com.samsung.android.bixby.agent
pm uninstall --user "$line" com.samsung.android.bixby.wakeup
pm uninstall --user "$line" com.samsung.android.bixbyvision.framework
pm uninstall --user "$line" com.samsung.android.brightnessbackupservice
pm uninstall --user "$line" com.samsung.android.callbgprovider
pm uninstall --user "$line" com.samsung.android.cameraxservice
pm uninstall --user "$line" com.samsung.android.carkey
pm uninstall --user "$line" com.samsung.android.da.daagent
pm uninstall --user "$line" com.samsung.android.dbsc
pm uninstall --user "$line" com.samsung.android.dck.timesync
pm uninstall --user "$line" com.samsung.android.dialer
pm uninstall --user "$line" com.samsung.android.dqagent
pm uninstall --user "$line" com.samsung.android.dsms
pm uninstall --user "$line" com.samsung.android.dynamiclock
pm uninstall --user "$line" com.samsung.android.easysetup
pm uninstall --user "$line" com.samsung.android.fast
pm uninstall --user "$line" com.samsung.android.forest
pm uninstall --user "$line" com.samsung.android.game.gametools
pm uninstall --user "$line" com.samsung.android.globalpostprocmgr
pm uninstall --user "$line" com.samsung.android.gru
pm uninstall --user "$line" com.samsung.android.hdmapp
pm uninstall --user "$line" com.samsung.android.hwresourceshare
pm uninstall --user "$line" com.samsung.android.hwresourceshare.storage
pm uninstall --user "$line" com.samsung.android.inputshare
pm uninstall --user "$line" com.samsung.android.intellivoiceservice
pm uninstall --user "$line" com.samsung.android.ipsgeofence
pm uninstall --user "$line" com.samsung.android.kidsinstaller
pm uninstall --user "$line" com.samsung.android.knox.analytics.uploader
pm uninstall --user "$line" com.samsung.android.knox.attestation
pm uninstall --user "$line" com.samsung.android.knox.containercore
pm uninstall --user "$line" com.samsung.android.knox.kpecore
pm uninstall --user "$line" com.samsung.android.knox.mpos
pm uninstall --user "$line" com.samsung.android.knox.pushmanager
pm uninstall --user "$line" com.samsung.android.knox.zt.framework
pm uninstall --user "$line" com.samsung.android.mapsagent
pm uninstall --user "$line" com.samsung.android.mcfds
pm uninstall --user "$line" com.samsung.android.mcfserver
pm uninstall --user "$line" com.samsung.android.mdecservice
pm uninstall --user "$line" com.samsung.android.mdm
pm uninstall --user "$line" com.samsung.android.mdx
pm uninstall --user "$line" com.samsung.android.mdx.kit
pm uninstall --user "$line" com.samsung.android.messaging
pm uninstall --user "$line" com.samsung.android.mobileservice
pm uninstall --user "$line" com.samsung.android.mocca
pm uninstall --user "$line" com.samsung.android.mydevice
pm uninstall --user "$line" com.samsung.android.net.wifi.wifiguider
pm uninstall --user "$line" com.samsung.android.networkdiagnostic
pm uninstall --user "$line" com.samsung.android.nfc
pm uninstall --user "$line" com.samsung.android.privateaccesstokens
pm uninstall --user "$line" com.samsung.android.provider.filterprovider
pm uninstall --user "$line" com.samsung.android.rampart
pm uninstall --user "$line" com.samsung.android.rubin.app
pm uninstall --user "$line" com.samsung.android.samsungpass
pm uninstall --user "$line" com.samsung.android.samsungpassautofill
pm uninstall --user "$line" com.samsung.android.samsungpositioning
pm uninstall --user "$line" com.samsung.android.scloud
pm uninstall --user "$line" com.samsung.android.scpm
pm uninstall --user "$line" com.samsung.android.sdk.handwriting
pm uninstall --user "$line" com.samsung.android.sdm.config
pm uninstall --user "$line" com.samsung.android.sead
pm uninstall --user "$line" com.samsung.android.server.wifi.mobilewips
pm uninstall --user "$line" com.samsung.android.service.peoplestripe
pm uninstall --user "$line" com.samsung.android.service.stplatform
pm uninstall --user "$line" com.samsung.android.service.tagservice
pm uninstall --user "$line" com.samsung.android.shortcutbackupservice
pm uninstall --user "$line" com.samsung.android.smartcallprovider
pm uninstall --user "$line" com.samsung.android.smartface
pm uninstall --user "$line" com.samsung.android.smartsuggestions
pm uninstall --user "$line" com.samsung.android.smartswitchassistant
pm uninstall --user "$line" com.samsung.android.spayfw
pm uninstall --user "$line" com.samsung.android.sskds
pm uninstall --user "$line" com.samsung.android.stickercenter
pm uninstall --user "$line" com.samsung.android.svcagent
pm uninstall --user "$line" com.samsung.android.themestore
pm uninstall --user "$line" com.samsung.android.video
pm uninstall --user "$line" com.samsung.android.vision.model
pm uninstall --user "$line" com.samsung.android.visionintelligence
pm uninstall --user "$line" com.samsung.android.visual.cloudcore
pm uninstall --user "$line" com.samsung.android.vtcamerasettings
pm uninstall --user "$line" com.samsung.android.wallpaper.live
pm uninstall --user "$line" com.samsung.app.newtrim
pm uninstall --user "$line" com.samsung.cmh
pm uninstall --user "$line" com.samsung.faceservice
pm uninstall --user "$line" com.samsung.gpuwatchapp
pm uninstall --user "$line" com.samsung.ipservice
pm uninstall --user "$line" com.samsung.knox.securefolder
pm uninstall --user "$line" com.samsung.petservice
pm uninstall --user "$line" com.samsung.safetyinformation
pm uninstall --user "$line" com.samsung.sait.sohservice
pm uninstall --user "$line" com.samsung.storyservice
pm uninstall --user "$line" com.samsung.videoscan
pm uninstall --user "$line" com.sec.android.CcInfo
pm uninstall --user "$line" com.sec.android.RilServiceModeApp
pm uninstall --user "$line" com.sec.android.app.SecSetupWizard
pm uninstall --user "$line" com.sec.android.app.billing
pm uninstall --user "$line" com.sec.android.app.bluetoothagent
pm uninstall --user "$line" com.sec.android.app.camera
pm uninstall --user "$line" com.sec.android.app.chromecustomizations
pm uninstall --user "$line" com.sec.android.app.desktoplauncher
pm uninstall --user "$line" com.sec.android.app.factorykeystring
pm uninstall --user "$line" com.sec.android.app.hwmoduletest
pm uninstall --user "$line" com.sec.android.app.magnifier
pm uninstall --user "$line" com.sec.android.app.parser
pm uninstall --user "$line" com.sec.android.app.qsfastpairoverlay
pm uninstall --user "$line" com.sec.android.app.quicktool
pm uninstall --user "$line" com.sec.android.app.samsungapps
pm uninstall --user "$line" com.sec.android.app.servicemodeapp
pm uninstall --user "$line" com.sec.android.app.setupwizardlegalprovider
pm uninstall --user "$line" com.sec.android.app.soundalive
pm uninstall --user "$line" com.sec.android.app.uwbtest
pm uninstall --user "$line" com.sec.android.app.ve.vebgm
pm uninstall --user "$line" com.sec.android.app.vepreload
pm uninstall --user "$line" com.sec.android.app.wlantest
pm uninstall --user "$line" com.sec.android.autodoodle.service
pm uninstall --user "$line" com.sec.android.daemonapp
pm uninstall --user "$line" com.sec.android.desktopmode.uiservice
pm uninstall --user "$line" com.sec.android.easyMover
pm uninstall --user "$line" com.sec.android.easyMover.Agent
pm uninstall --user "$line" com.sec.android.easyonehand
pm uninstall --user "$line" com.sec.android.gallery3d
pm uninstall --user "$line" com.sec.android.iaft
pm uninstall --user "$line" com.sec.android.llmpolicy
pm uninstall --user "$line" com.sec.android.mimage.avatarstickers
pm uninstall --user "$line" com.sec.android.mimage.photoretouching
pm uninstall --user "$line" com.sec.android.provider.badge
pm uninstall --user "$line" com.sec.android.smartfpsadjuster
pm uninstall --user "$line" com.sec.android.widgetapp.easymodecontactswidget
pm uninstall --user "$line" com.sec.app.RilErrorNotifier
pm uninstall --user "$line" com.sec.bcservice
pm uninstall --user "$line" com.sec.epdgtestapp
pm uninstall --user "$line" com.sec.facatfunction
pm uninstall --user "$line" com.sec.factory.camera
pm uninstall --user "$line" com.sec.imslogger
pm uninstall --user "$line" com.sec.location.nfwlocationprivacy
pm uninstall --user "$line" com.sec.modem.settings
pm uninstall --user "$line" com.sec.phone
pm uninstall --user "$line" com.sec.spp.push
pm uninstall --user "$line" com.sec.unifiedwfc
pm uninstall --user "$line" com.sec.usbsettings
pm uninstall --user "$line" com.sec.vsim.ericssonnsds.webapp
pm uninstall --user "$line" com.sem.factoryapp
pm uninstall --user "$line" com.skms.android.agent
pm uninstall --user "$line" com.swiftkey.swiftkeyconfigurator
pm uninstall --user "$line" com.tencent.soter.soterserver
pm uninstall --user "$line" com.touchtype.swiftkey
pm uninstall --user "$line" com.wsomacp
pm uninstall --user "$line" org.ifaa.aidl.manager
done <<EOF
$(pm list users | tail -n+2 | sed 's/^.*UserInfo{//; s/:.*}.*$//')
EOF
